"""last_Name changed on last_name

Revision ID: 59700a3041f6
Revises: cdb9dbe8285d
Create Date: 2021-03-08 16:46:17.794462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59700a3041f6'
down_revision = 'cdb9dbe8285d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.drop_column('user', 'last_Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_Name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
